In [1]:
import numpy as np 
import torch

In [7]:
# numpy와 명령어가 비슷

a = torch.arange(9)
a = a.reshape(3, 3)
a.numpy()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int64)

In [10]:
randoms = torch.rand((3, 3))
randoms

tensor([[0.9860, 0.6330, 0.1094],
        [0.3093, 0.2646, 0.9426],
        [0.7224, 0.6868, 0.8666]])

In [11]:
zeros = torch.zeros((3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
a * 3
a + 3
a + a

torch.add(a, 10)

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [21]:
range_nums = torch.arange(9).reshape(3, 3)
# view = reshape 근데 reshape 사용 권장하고있으니 그냥 reshape 사용해
print(range_nums)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [28]:
range_nums[1:2, 2]

# 토치에서 넘파이로 넘파이에서 토치로
a = a.numpy()
torch.from_numpy(a)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])