In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 1], [1, 1, 1]])

print(arr.shape)

(2, 3)


In [7]:
arr = np.array([
[[[1, 1, 1], [1, 1, 1], [1, 1, 1]],
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]],
[[[2, 2, 2], [2, 2, 2], [2, 2, 2]],
[[2, 2, 2], [2, 2, 2], [2, 2, 2]]]
]
)

print(arr.shape)


(2, 2, 3, 3)


In [8]:
arr = np.array([ [[1], [2], [3]], [[1], [2], [3]], [[1], [2], [3]] ])
print(arr.shape)


(3, 3, 1)


In [19]:
arr = np.arange(9).reshape(3, 3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [24]:
arr = np.random.randint(3, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(4, size=9).reshape(3, 3)

arr = arr + arr_2
print(arr)

[[[2 2 3]
  [1 3 3]
  [3 2 1]]

 [[1 1 2]
  [3 3 2]
  [1 2 2]]

 [[2 3 4]
  [2 3 4]
  [1 3 2]]]


In [27]:
np.sum(arr, axis=1)

array([[ 6,  7,  7],
       [ 5,  6,  6],
       [ 5,  9, 10]])

In [29]:
arr = np.arange(32)
v = arr.reshape([4, 2, 4])
print(v)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]


In [38]:
np.sum(v, -1)

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])

In [63]:

arr = np.arange(32).reshape(4, 2, 4)

arr = np.expand_dims(arr, -1)

print(arr.shape)

(4, 2, 4)
