In [2]:
import numpy as np
import tensorflow as tf

In [6]:
#numpy
arr = [[1,2,3], [4,5,6]]
arr= np.array(arr)

In [20]:
#tensorflow
tensor = tf.constant(arr)
tf.constant(((1,2,3), (4,5,6)), dtype=tf.float32) #tuple도 가능하며, 데이터타입 지정가능


tf.cast(tensor, dtype=tf.uint8) #np.astype과 같이 tf에서는 tf.cast

<tf.Tensor: shape=(2, 3), dtype=uint8, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)>

In [22]:
tensor.shape
tensor.dtype

tf.int32

In [25]:
# tensor <-> numpy
np.array(tensor)
tensor.numpy()

type(tensor.numpy())

numpy.ndarray

In [102]:
np.random.randn(9) # 표준정규분포에서 9개의 난수 추출
# np.random.uniform(최소, 최대, 개수) # 9보다 작은 임의의 난수 추출

tf.random.normal([3, 3]) # 표준정규분포에서 난수추출
tf.random.uniform([3, 3]) # 0~1사이 랜덤값 추출, param설정으로 범위 변경 가능 minval = 10


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.03743064, 0.13103056, 0.13187253],
       [0.3914876 , 0.35653675, 0.17788851],
       [0.970153  , 0.5195459 , 0.02306914]], dtype=float32)>